package Eleccion;


/**
* Eleccion/NodeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Eleccion.idl
* Friday, November 25, 2011 8:45:37 PM CST
*/

public interface NodeOperations 
{
  void register (Eleccion.Node nodo, int id, int lado);
  void removeNode (Eleccion.Node nodo);
  void message (String msg);
  void election ();
  void reply (String msg);
  void relay (String msg);
  int getLeader ();
} // interface NodeOperations
