package Eleccion;


/**
* Eleccion/Node.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Eleccion.idl
* Friday, November 25, 2011 8:45:37 PM CST
*/

public interface Node extends NodeOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Node
